### ISSUE TITLE
code reusing for Android app

### ISSUE THREAD

**Issue by paradite** [kanghj/fyp-chrome-extension#2]
Hi Hong Jin, as you probably already know, I will be working on the Android client for Word News project. 

I am trying to use WebView as the main UI for the app, and your code for Chrome extension seems be well-fitted for re-implementing the features in Android app. In fact, I was able to get the basic functions working with minimal changes. Hence, I am requesting the permission to reuse and modify some of your code to be used in the Android client.

**Comment by kanghj** [comment]
Hi Zhu Liang,

Go ahead and modify the code. Code quality can be quite poor, so let me know if you need me to refactor/rewrite or explain any part of the code. Good luck for your project!

**Comment by kite1988** [comment]
Hi Hong Jin,

Can you also transfer the ownership of wordnews_chrome_extension
https://github.com/kanghj/wordnews_chrome_extension and wordnews_server
https://github.com/kanghj/wordnews_server to WING-NUS when convenient ?

Thanks!
Tao

**Comment by kanghj** [comment]
These repositories are forks of the original repositories of https://github.com/endlessfrank/translate_app_ror and https://github.com/laizhouxia/fyp-chrome-extension though, so it should be better if we transfer those repositories instead. I will push my code to the original repos once they are transferred. @endlessfrank @laizhouxia.

**Comment by kanghj** [comment]
Alternatively, I can simply push to a new repository owned by WING-NUS if they are not contactable

**Comment by knmnyn** [comment]
Hi all:

This issue needs to be brought to some closure.  Chun Keat reminded me just
now that it is not resolved.

WordNews/clients/14-android - `git subtree add
--prefix=clients/14-angular
https://github.com/endlessfrank/translate_heroku_extension.git master`
                /15-android - `git subtree add
--prefix=clients/15-angular
https://github.com/laizhouxia/fyp-chrome-extension.git master`
                /16-android - this original WordNews repository
(before renaming).
        /server/ - server code - `git subtree add --prefix=server
https://github.com/kanghj/wordnews_server.git master`
        /datasets/ - for experimental datasets
        /pubs/ - for our publications
             /nlp-tea-2015 - git subtree add
--prefix=pubs/nlp-tea-2015
ssh://wing.nus@cte.comp.nus.edu.sg/home/wing.nus/GITRepositories/wing.nus/nlp-tea-2015
master
             /nlp-tea-2016 - git subtree add
--prefix=pubs/nlp-tea-2016 https://git.overleaf.com/5399480qspfqg
master

        /lib/ - for dependent libraries

Please push to these places to update.  Zhu Liang, you may want to either
push on top of the existing android directory or create a new directory,
e.g., 17-android, for storing your code.

Please add the corresponding datasets and files under datasets and
dependent libraries under lib.  Thanks!

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885 <6516%201885>(DID) :: +65 6779 4580
<6779%204580> (Fax) :: kanmy@comp.nus.edu.sg (E) ::
www.comp.nus.edu.sg/~kanmy (W)

**Comment by paradite** [comment]
I have transferred the ownership of WordNews Android client to NUS Wing:

https://github.com/WING-NUS/Word-News-Android

**Comment by knmnyn** [comment]
Hi all:

Thanks for this, Zhu Liang.  I've put it into the subtree for WordNews.
Hopefully that can be kept up-to-date.


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)
