### ISSUE TITLE
code quality issues 

### ISSUE THREAD

**Issue by paradite** [kanghj/fyp-chrome-extension#5]
Hi, Kong Jing, as you already know, the current JavaScript code suffers from serious code quality issues
- nested for loops
- long functions
- lots of unnecessary extra DOM selections

I want to do some refactoring, but that would cause the code to be out of sync with the current master. 
Is it better if we can somehow use a single JavaScript code of https://github.com/kanghj/wordnews_chrome_extension/blob/master/contentscript.js
for both the extension and Android client and provide different entry points (like what I did with `init` function and you did with `chrome.storage.sync`. 
This way we can both refactor the single code base.

**Comment by kanghj** [comment]
Yes, that will definitely be better. I don't have time to work on this the next couple of days though, but I'll add you as a collaborator to this repo so you can do what you want.

**Comment by paradite** [comment]
with single code base for Android and extension now, we can work on improving the code quality.
